---
- hosts: app_servers
  become: yes
  vars:
    current_version: "{{ build_version }}"
    app_symlink: "{{ deploy_path }}/current"
  
  roles:
    - apache
    - angular
    # Uncomment below if MariaDB is needed
    # - mariadb