---
- name: Rollback Angular App to Specified Version
  hosts: app_servers
  become: yes
  vars:
    app_symlink: "{{ deploy_path }}/current"

  tasks:
    - name: Check if rollback version exists on server
      stat:
        path: "{{ deploy_path }}/versions/{{ rollback_version }}"
      register: version_stat

    - name: Fail if version doesn't exist
      fail:
        msg: "Version {{ rollback_version }} does not exist on the server"
      when: not version_stat.stat.exists

    - name: Update symlink to rollback version
      file:
        src: "{{ deploy_path }}/versions/{{ rollback_version }}"
        dest: "{{ app_symlink }}"
        state: link
        force: yes

    - name: Set correct permissions on the rolled back version
      file:
        path: "{{ deploy_path }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Restart Apache to apply rollback
      service:
        name: apache2
        state: restarted
