---
- name: Ensure deployment base directory exists
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Ensure versioned subdirectory exists on target
  file:
    path: "{{ deploy_path }}/versions/{{ build_version }}"
    state: directory
    mode: '0755'

- name: Copy artifact from Jenkins to target server
  delegate_to: localhost
  copy:
    src: "{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}/{{ provided_artifact_name }}"
    remote_src: no

- name: Extract artifact on target server
  unarchive:
    src: "{{ deploy_path }}/versions/{{ build_version }}/{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}"
    remote_src: yes
    creates: "{{ deploy_path }}/versions/{{ build_version }}/index.html"

- name: Update 'current' symlink to point to latest version
  file:
    src: "{{ deploy_path }}/versions/{{ build_version }}"
    dest: "{{ app_symlink }}"
    state: link
    force: yes

- name: Ensure correct permissions on deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
