- name: Ensure base deployment directory exists on target
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Ensure versioned release directory exists on target
  file:
    path: "{{ deploy_path }}/versions/{{ build_version }}"
    state: directory
    mode: '0755'
  delegate_to: n1

- name: Transfer artifact from Jenkins to target server
  delegate_to: localhost
  synchronize:
    src: "{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}/"
    mode: push

- name: Extract artifact on target server
  unarchive:
    src: "{{ deploy_path }}/versions/{{ build_version }}/{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}"
    remote_src: yes
    creates: "{{ deploy_path }}/versions/{{ build_version }}/index.html"

- name: Update 'current' symlink to point to latest version
  file:
    src: "{{ deploy_path }}/versions/{{ build_version }}"
    dest: "{{ app_symlink }}"
    state: link
    force: yes

- name: Set proper permissions on deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
