---
- name: Create deployment base directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Create version-specific directory
  file:
    path: "{{ deploy_path }}/versions/{{ build_version }}"
    state: directory
    mode: '0755'

- name: Copy artifact from Jenkins to target
  delegate_to: localhost  # Runs on Jenkins (control node)
  copy:
    src: "{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}/{{ provided_artifact_name }}"
    remote_src: no  # Artifact is local to Jenkins

- name: Extract artifact into versioned directory
  unarchive:
    src: "{{ deploy_path }}/versions/{{ build_version }}/{{ provided_artifact_name }}"
    dest: "{{ deploy_path }}/versions/{{ current_version }}"
    remote_src: yes
    creates: "{{ deploy_path }}/versions/{{ current_version }}"

- name: Update 'current' symlink to latest version
  file:
    src: "{{ deploy_path }}/versions/{{ current_version }}"
    dest: "{{ app_symlink }}"
    state: link
    force: yes

- name: Set permissions for deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
