- name: Create deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Create versions directory
  file:
    path: "{{ deploy_path }}/versions/{{ build_version }}"
    state: directory
    mode: '0755'

- name: Copy artifact to server
  delegate_to: localhost
  copy:
    src: "{{ artifact_path }}"
    dest: "{{ deploy_path }}/versions/{{ build_version }}/{{ app_name }}-{{ build_version }}.tar.gz"
    remote_src: no

- name: Extract artifact to versioned directory
  unarchive:
    src: "{{ deploy_path }}/versions/{{ build_version }}/{{ app_name }}-{{ build_version }}.tar.gz"
    dest: "{{ deploy_path }}/versions/{{ current_version }}"
    remote_src: yes
    creates: "{{ deploy_path }}/versions/{{ current_version }}/index.html"

- name: Update symlink to current version
  file:
    src: "{{ deploy_path }}/versions/{{ current_version }}"
    dest: "{{ app_symlink }}"
    state: link
    force: yes

- name: Set permissions for web content
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
