---
- name: Create base deployment directory
  file:
    path: "/var/www/html/"
    state: directory
    mode: '0755'
  become: yes

- name: Create version directory
  file:
    path: "/var/www/html/{{ angular_app_version }}"
    state: directory
    mode: '0755'
  become: yes

- name: Create versions directory
  file:
    path: "/var/www/html/versions/{{ angular_app_version }}"
    state: directory
    mode: '0755'
  become: yes

- name: Copy artifact
  copy:
    src: "angular_build_{{ angular_app_version }}.tar.gz"
    dest: "/tmp/angular_build_{{ angular_app_version }}.tar.gz"

- name: Ensure the artifact is present
  stat:
    path: "/tmp/angular_build_{{ angular_version }}.tar.gz"
  register: artifact_stat

- name: Fail if artifact is missing
  fail:
    msg: "The build artifact {{ angular_version }}.tar.gz was not found!"
  when: not artifact_stat.stat.exists

- name: Extract Angular app archive
  unarchive:
    src: "/tmp/angular_build_{{ angular_version }}.tar.gz"
    dest: "/var/www/html/{{ angular_app_version }}"
    remote_src: yes
    become: yes

- name: Set correct permissions on the extracted app files
  file:
    path: "/var/www/html/{{ angular_app_version }}"
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes

- name: Current/Update symlink to current version
  file:
    src: "/var/www/html/{{ angular_app_version }}"
    dest: "/var/www/html/current"
    state: link
    force: yes
  become: yes
...