---
- name: Create deployment directory
  file:
    path: "/var/www/html/{{ angular_app_version }}"
    state: directory
    mode: '0755'
  with_items:
    - "/var/www/html"
    - "/var/www/html/{{ angular_app_version }}"
  become: yes

- name: Create versions directory
  file:
    path: "/var/www/html/versions/{{ angular_app_version }}"
    state: directory
    mode: '0755'
  become: yes

- name: Copy artifact
  copy:
    src: "angular_build_{{ angular_version }}.tar.gz"
    dest: "/tmp/angular_build_{{ angular_version }}.tar.gz"

- name: Extract Angular app archive
  unarchive:
    src: "/tmp/angular_build_{{ angular_version }}.tar.gz"
    dest: "/var/www/html/{{ angular_app_version }}"
    remote_src: yes
    become: yes

- name: Current/Update symlink to current version
  file:
    src: "/var/www/html/{{ angular_app_version }}"
    dest: "/var/www/html/current"
    state: link
    force: yes
  become: yes
...