---
# tasks file for Apache



- name: Install Apache
  apt:
    name: apache2
    state: present
    become: true

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes

...
