---
- name: Create deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Create versions directory
  file:
    path: "{{ deploy_path }}/versions"
    state: directory
    mode: '0755'

- name: Copy artifact to server
  copy:
    src: "{{ artifact_path }}"
    dest: "/tmp/{{ artifact_path }}"
    remote_src: yes  # Assuming artifact is on Jenkins server

- name: Extract artifact to versioned directory
  unarchive:
    src: "/tmp/{{ artifact_path }}"
    dest: "{{ deploy_path }}/versions/{{ current_version }}"
    remote_src: yes
    creates: "{{ deploy_path }}/versions/{{ current_version }}"

- name: Update symlink to current version
  file:
    src: "{{ deploy_path }}/versions/{{ current_version }}"
    dest: "{{ app_symlink }}"
    state: link
    force: yes

- name: Set permissions for web content
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
...