---
- name: Create application directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - /var/www/html/{{ app_name }}
    - /var/www/html/{{ app_name }}/releases
    - /var/www/html/{{ app_name }}/shared

- name: Upload and extract artifact
  unarchive:
    src: "{{ artifact_name }}"
    dest: /var/www/html/{{ app_name }}/releases/{{ build_version }}
    remote_src: yes
    owner: www-data
    group: www-data

- name: Update current symlink to new version
  file:
    src: /var/www/html/{{ app_name }}/releases/{{ build_version }}
    dest: /var/www/html/{{ app_name }}/current
    state: link
    force: yes

...